# Generated by Django 3.0.6 on 2020-06-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20200607_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
