# Generated by Django 3.0.6 on 2020-06-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_services_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
