# Generated by Django 3.0.6 on 2020-06-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20200607_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='upload_pic',
            field=models.ImageField(blank=True, default='static/images/cat.jpg', null=True, upload_to='pic_folder/'),
        ),
    ]
