# Generated by Django 3.0.6 on 2020-06-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_auto_20200607_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='upload_pic',
            field=models.ImageField(blank=True, default='images/cat.jpg', null=True, upload_to='images/'),
        ),
    ]
