# Generated by Django 3.0.6 on 2020-06-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_auto_20200607_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='upload_pic',
            field=models.ImageField(blank=True, default='images/chiks.jpg', null=True, upload_to='images/'),
        ),
    ]
