# Generated by Django 3.0.6 on 2020-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_auto_20200607_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slider_pic_upload',
            field=models.ImageField(blank=True, default='static/images/a2.jpg', null=True, upload_to='static/images/'),
        ),
    ]
