# Generated by Django 3.0.6 on 2020-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_services_slider_pic_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_pic_upload', models.ImageField(blank=True, default='static/images/a2.jpg', null=True, upload_to='static/slider_pics/')),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='slider_pic_upload',
        ),
    ]
