# Generated by Django 3.0.6 on 2020-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_auto_20200607_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_pic_upload',
            field=models.ImageField(default='static/images/a2.jpg', upload_to='static/slider_pics/'),
        ),
    ]
