# Generated by Django 3.0.6 on 2020-06-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_auto_20200607_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pic', models.ImageField(default='static/images/a2.jpg', upload_to='static/gallery/')),
            ],
        ),
    ]
