# Generated by Django 3.0.6 on 2020-06-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
