# Generated by Django 3.0.6 on 2020-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_gallery_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='img_url',
        ),
        migrations.AddField(
            model_name='gallery',
            name='pic_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='pic_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='upload_video',
            field=models.FileField(blank=True, default='static/images/chiks.jpg', null=True, upload_to='static/videos/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='pic_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
