# Generated by Django 3.0.6 on 2020-06-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_auto_20200607_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='upload_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='static/videos/'),
        ),
    ]
