# Generated by Django 3.0.6 on 2020-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_auto_20200612_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.CharField(blank=True, default='Dj studio', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='upload_pic',
            field=models.ImageField(default='static/images/a2.jpg', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='upload_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_pic_upload',
            field=models.ImageField(default='static/images/a2.jpg', upload_to='slider_pics/'),
        ),
    ]
