# Generated by Django 3.0.7 on 2020-07-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0021_auto_20200625_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='upload_pic',
            field=models.ImageField(default='images/a2.jpg', upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='upload_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_pic_upload',
            field=models.ImageField(default='images/a2.jpg', upload_to='slider_pics/'),
        ),
    ]
