# Generated by Django 3.0.7 on 2020-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0024_auto_20200717_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='upload_pic',
            field=models.ImageField(default='images/others/a2.jpg', upload_to='images/gallery/'),
        ),
    ]
