# Generated by Django 3.0.7 on 2020-07-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0025_auto_20200717_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='upload_pic',
            field=models.ImageField(default='media/images/a2.jpg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='upload_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/videos/'),
        ),
    ]
